/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTransactionsRouteImport } from './routes/app.transactions'
import { Route as AppSpendingRouteImport } from './routes/app.spending'
import { Route as AppPaymentScheduleRouteImport } from './routes/app.payment-schedule'
import { Route as AppMoreRouteImport } from './routes/app.more'
import { Route as AppInstitutionsRouteImport } from './routes/app.institutions'
import { Route as AppEverythingRouteImport } from './routes/app.everything'
import { Route as AppDebtsRouteImport } from './routes/app.debts'
import { Route as AppDebtStrategyRouteImport } from './routes/app.debt-strategy'
import { Route as AppBillsRouteImport } from './routes/app.bills'
import { Route as AppAccountsRouteImport } from './routes/app.accounts'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSpendingRoute = AppSpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentScheduleRoute = AppPaymentScheduleRouteImport.update({
  id: '/payment-schedule',
  path: '/payment-schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppInstitutionsRoute = AppInstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => AppRoute,
} as any)
const AppEverythingRoute = AppEverythingRouteImport.update({
  id: '/everything',
  path: '/everything',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtsRoute = AppDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtStrategyRoute = AppDebtStrategyRouteImport.update({
  id: '/debt-strategy',
  path: '/debt-strategy',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/bills': typeof AppBillsRoute
  '/app/debt-strategy': typeof AppDebtStrategyRoute
  '/app/debts': typeof AppDebtsRoute
  '/app/everything': typeof AppEverythingRoute
  '/app/institutions': typeof AppInstitutionsRoute
  '/app/more': typeof AppMoreRoute
  '/app/payment-schedule': typeof AppPaymentScheduleRoute
  '/app/spending': typeof AppSpendingRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/bills': typeof AppBillsRoute
  '/app/debt-strategy': typeof AppDebtStrategyRoute
  '/app/debts': typeof AppDebtsRoute
  '/app/everything': typeof AppEverythingRoute
  '/app/institutions': typeof AppInstitutionsRoute
  '/app/more': typeof AppMoreRoute
  '/app/payment-schedule': typeof AppPaymentScheduleRoute
  '/app/spending': typeof AppSpendingRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/bills': typeof AppBillsRoute
  '/app/debt-strategy': typeof AppDebtStrategyRoute
  '/app/debts': typeof AppDebtsRoute
  '/app/everything': typeof AppEverythingRoute
  '/app/institutions': typeof AppInstitutionsRoute
  '/app/more': typeof AppMoreRoute
  '/app/payment-schedule': typeof AppPaymentScheduleRoute
  '/app/spending': typeof AppSpendingRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/accounts'
    | '/app/bills'
    | '/app/debt-strategy'
    | '/app/debts'
    | '/app/everything'
    | '/app/institutions'
    | '/app/more'
    | '/app/payment-schedule'
    | '/app/spending'
    | '/app/transactions'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/accounts'
    | '/app/bills'
    | '/app/debt-strategy'
    | '/app/debts'
    | '/app/everything'
    | '/app/institutions'
    | '/app/more'
    | '/app/payment-schedule'
    | '/app/spending'
    | '/app/transactions'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/accounts'
    | '/app/bills'
    | '/app/debt-strategy'
    | '/app/debts'
    | '/app/everything'
    | '/app/institutions'
    | '/app/more'
    | '/app/payment-schedule'
    | '/app/spending'
    | '/app/transactions'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/spending': {
      id: '/app/spending'
      path: '/spending'
      fullPath: '/app/spending'
      preLoaderRoute: typeof AppSpendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payment-schedule': {
      id: '/app/payment-schedule'
      path: '/payment-schedule'
      fullPath: '/app/payment-schedule'
      preLoaderRoute: typeof AppPaymentScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/more': {
      id: '/app/more'
      path: '/more'
      fullPath: '/app/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/institutions': {
      id: '/app/institutions'
      path: '/institutions'
      fullPath: '/app/institutions'
      preLoaderRoute: typeof AppInstitutionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/everything': {
      id: '/app/everything'
      path: '/everything'
      fullPath: '/app/everything'
      preLoaderRoute: typeof AppEverythingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debts': {
      id: '/app/debts'
      path: '/debts'
      fullPath: '/app/debts'
      preLoaderRoute: typeof AppDebtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debt-strategy': {
      id: '/app/debt-strategy'
      path: '/debt-strategy'
      fullPath: '/app/debt-strategy'
      preLoaderRoute: typeof AppDebtStrategyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bills': {
      id: '/app/bills'
      path: '/bills'
      fullPath: '/app/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppBillsRoute: typeof AppBillsRoute
  AppDebtStrategyRoute: typeof AppDebtStrategyRoute
  AppDebtsRoute: typeof AppDebtsRoute
  AppEverythingRoute: typeof AppEverythingRoute
  AppInstitutionsRoute: typeof AppInstitutionsRoute
  AppMoreRoute: typeof AppMoreRoute
  AppPaymentScheduleRoute: typeof AppPaymentScheduleRoute
  AppSpendingRoute: typeof AppSpendingRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppBillsRoute: AppBillsRoute,
  AppDebtStrategyRoute: AppDebtStrategyRoute,
  AppDebtsRoute: AppDebtsRoute,
  AppEverythingRoute: AppEverythingRoute,
  AppInstitutionsRoute: AppInstitutionsRoute,
  AppMoreRoute: AppMoreRoute,
  AppPaymentScheduleRoute: AppPaymentScheduleRoute,
  AppSpendingRoute: AppSpendingRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
