/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAccountsRouteImport } from './routes/app.accounts'
import { Route as AppBillsRouteImport } from './routes/app.bills'
import { Route as AppCategoriesRouteImport } from './routes/app.categories'
import { Route as AppDebtStrategyRouteImport } from './routes/app.debt-strategy'
import { Route as AppDebtsRouteImport } from './routes/app.debts'
import { Route as AppEverythingRouteImport } from './routes/app.everything'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppInstitutionsRouteImport } from './routes/app.institutions'
import { Route as AppMoreRouteImport } from './routes/app.more'
import { Route as AppPaycheckRouteImport } from './routes/app.paycheck'
import { Route as AppPaymentScheduleRouteImport } from './routes/app.payment-schedule'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSnapshotRouteImport } from './routes/app.snapshot'
import { Route as AppSpendingRouteImport } from './routes/app.spending'
import { Route as AppTransactionsRouteImport } from './routes/app.transactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtStrategyRoute = AppDebtStrategyRouteImport.update({
  id: '/debt-strategy',
  path: '/debt-strategy',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtsRoute = AppDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => AppRoute,
} as any)
const AppEverythingRoute = AppEverythingRouteImport.update({
  id: '/everything',
  path: '/everything',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppInstitutionsRoute = AppInstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppPaycheckRoute = AppPaycheckRouteImport.update({
  id: '/paycheck',
  path: '/paycheck',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentScheduleRoute = AppPaymentScheduleRouteImport.update({
  id: '/payment-schedule',
  path: '/payment-schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSnapshotRoute = AppSnapshotRouteImport.update({
  id: '/snapshot',
  path: '/snapshot',
  getParentRoute: () => AppRoute,
} as any)
const AppSpendingRoute = AppSpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/bills': typeof AppBillsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/debt-strategy': typeof AppDebtStrategyRoute
  '/app/debts': typeof AppDebtsRoute
  '/app/everything': typeof AppEverythingRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/institutions': typeof AppInstitutionsRoute
  '/app/more': typeof AppMoreRoute
  '/app/paycheck': typeof AppPaycheckRoute
  '/app/payment-schedule': typeof AppPaymentScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/snapshot': typeof AppSnapshotRoute
  '/app/spending': typeof AppSpendingRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/bills': typeof AppBillsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/debt-strategy': typeof AppDebtStrategyRoute
  '/app/debts': typeof AppDebtsRoute
  '/app/everything': typeof AppEverythingRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/institutions': typeof AppInstitutionsRoute
  '/app/more': typeof AppMoreRoute
  '/app/paycheck': typeof AppPaycheckRoute
  '/app/payment-schedule': typeof AppPaymentScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/snapshot': typeof AppSnapshotRoute
  '/app/spending': typeof AppSpendingRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/bills': typeof AppBillsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/debt-strategy': typeof AppDebtStrategyRoute
  '/app/debts': typeof AppDebtsRoute
  '/app/everything': typeof AppEverythingRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/institutions': typeof AppInstitutionsRoute
  '/app/more': typeof AppMoreRoute
  '/app/paycheck': typeof AppPaycheckRoute
  '/app/payment-schedule': typeof AppPaymentScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/snapshot': typeof AppSnapshotRoute
  '/app/spending': typeof AppSpendingRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/accounts'
    | '/app/bills'
    | '/app/categories'
    | '/app/debt-strategy'
    | '/app/debts'
    | '/app/everything'
    | '/app/goals'
    | '/app/institutions'
    | '/app/more'
    | '/app/paycheck'
    | '/app/payment-schedule'
    | '/app/settings'
    | '/app/snapshot'
    | '/app/spending'
    | '/app/transactions'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/accounts'
    | '/app/bills'
    | '/app/categories'
    | '/app/debt-strategy'
    | '/app/debts'
    | '/app/everything'
    | '/app/goals'
    | '/app/institutions'
    | '/app/more'
    | '/app/paycheck'
    | '/app/payment-schedule'
    | '/app/settings'
    | '/app/snapshot'
    | '/app/spending'
    | '/app/transactions'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/accounts'
    | '/app/bills'
    | '/app/categories'
    | '/app/debt-strategy'
    | '/app/debts'
    | '/app/everything'
    | '/app/goals'
    | '/app/institutions'
    | '/app/more'
    | '/app/paycheck'
    | '/app/payment-schedule'
    | '/app/settings'
    | '/app/snapshot'
    | '/app/spending'
    | '/app/transactions'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bills': {
      id: '/app/bills'
      path: '/bills'
      fullPath: '/app/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories': {
      id: '/app/categories'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debt-strategy': {
      id: '/app/debt-strategy'
      path: '/debt-strategy'
      fullPath: '/app/debt-strategy'
      preLoaderRoute: typeof AppDebtStrategyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debts': {
      id: '/app/debts'
      path: '/debts'
      fullPath: '/app/debts'
      preLoaderRoute: typeof AppDebtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/everything': {
      id: '/app/everything'
      path: '/everything'
      fullPath: '/app/everything'
      preLoaderRoute: typeof AppEverythingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/institutions': {
      id: '/app/institutions'
      path: '/institutions'
      fullPath: '/app/institutions'
      preLoaderRoute: typeof AppInstitutionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/more': {
      id: '/app/more'
      path: '/more'
      fullPath: '/app/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/paycheck': {
      id: '/app/paycheck'
      path: '/paycheck'
      fullPath: '/app/paycheck'
      preLoaderRoute: typeof AppPaycheckRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payment-schedule': {
      id: '/app/payment-schedule'
      path: '/payment-schedule'
      fullPath: '/app/payment-schedule'
      preLoaderRoute: typeof AppPaymentScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/snapshot': {
      id: '/app/snapshot'
      path: '/snapshot'
      fullPath: '/app/snapshot'
      preLoaderRoute: typeof AppSnapshotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/spending': {
      id: '/app/spending'
      path: '/spending'
      fullPath: '/app/spending'
      preLoaderRoute: typeof AppSpendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppBillsRoute: typeof AppBillsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppDebtStrategyRoute: typeof AppDebtStrategyRoute
  AppDebtsRoute: typeof AppDebtsRoute
  AppEverythingRoute: typeof AppEverythingRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppInstitutionsRoute: typeof AppInstitutionsRoute
  AppMoreRoute: typeof AppMoreRoute
  AppPaycheckRoute: typeof AppPaycheckRoute
  AppPaymentScheduleRoute: typeof AppPaymentScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSnapshotRoute: typeof AppSnapshotRoute
  AppSpendingRoute: typeof AppSpendingRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppBillsRoute: AppBillsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppDebtStrategyRoute: AppDebtStrategyRoute,
  AppDebtsRoute: AppDebtsRoute,
  AppEverythingRoute: AppEverythingRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppInstitutionsRoute: AppInstitutionsRoute,
  AppMoreRoute: AppMoreRoute,
  AppPaycheckRoute: AppPaycheckRoute,
  AppPaymentScheduleRoute: AppPaymentScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSnapshotRoute: AppSnapshotRoute,
  AppSpendingRoute: AppSpendingRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
